             ____   ___   ___ _  __  _
            |  _ \ / _ \ / __| |/ / | |   _ _ __  _   _ _  _
            | . _/| | | | |  | '_/  | |  |_| '_ \| | | | \/ |
            | |\ \| |_| | |__| . \  | |__| | | | | `_' |>  <
            |_| \_\ ___/ \___|_|\_\ |____|_|_| |_|\___/|_/\_|
         [============> http://www.rocklinux.org/ <============]

Help Screens:
-------------

      <1>                      Installation overview
      <0>                      This help-text

Actions:
--------

      <ENTER>                  Start installation
      install options <Enter>  Start install with the given kernel options
      help                     Show SILO's help

